<Project>
  <Target Name="ImpulsaIncludeProjectPriInPublish"
          BeforeTargets="ComputeResolvedFilesToPublishList"
          DependsOnTargets="$(GenerateProjectPriFile)">
    <ItemGroup>
      <ResolvedFileToPublish Include="$(ProjectPriFullPath)"
                             Condition="Exists('$(ProjectPriFullPath)')">
        <RelativePath>$(ProjectPriFileName)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
